#!/bin/sh

# Make rbenv work on weird environments
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null 2>&1; then
    eval "$(rbenv init -)"

    export RBENV_VERSION=`cat .rbenv-version`
    exec_cmd="rbenv exec"
fi
export RBENV_DEBUG=1
rbenv exec bundle install 2>&1 | tee bundle_debug.log
rbenv exec gem env 2>&1 | tee gem_debug.log
