#!/bin/bash

set -x
set -e

export PATH="$HOME/.rbenv/bin:$PATH"

if which rbenv > /dev/null 2>&1; then
    eval "$(rbenv init -)"

    export RBENV_VERSION=`cat .rbenv-version`
    exec_cmd="rbenv exec"
fi

ruby --version

$exec_cmd bundle install
$exec_cmd bundle exec rake spec
