#!/bin/sh

# Make rbenv work on weird environments
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null 2>&1; then
    eval "$(rbenv init -)"

    export RBENV_VERSION=`cat .rbenv-version`
    exec_cmd="rbenv exec"
fi

export BUNDLE_GEMFILE=`pwd`/Gemfile
echo "--"
env
echo "--"
pwd
$exec_cmd bundle config
$exec_cmd bundle check
$exec_cmd bundle install --path .bundle
$exec_cmd bundle exec rake spec
